# $NetBSD: MAKEDEV.conf,v 1.4 2020/08/09 00:56:44 tsutsui Exp $

all_md)
	makedev com0 com1 com2 com3 com4 com5 com6 com7
	makedev wd0 wd1
	makedev atabus0
	makedev sd0 sd1 sd2 sd3 cd0 st0 st1
	makedev ttyC0 ttyC1 ttyC2 ttyC3 ttyC4 ttyC5 ttyC6 ttyC7
	makedev romcons
	;;