#!/bin/sh
#
# $NetBSD: wrap030,v 1.5 2015/03/30 10:58:37 techav Exp $
#
# this is intended to be a one-stop lightweight rc script to get the system up
# and running as quickly as possible. it replaces all other scripts in rc.d
#

# PROVIDE: wrap030

$_rc_subr_loaded . /etc/rc.subr

name="wrap030"
start_cmd="wrap030_start"
stop_cmd="wrap030_stop"

ldconfig_command="/sbin/ldconfig"

wrap030_start()
{
	printf "root ... "
	umount -a >/dev/null 2>&1
	mount /
	printf "OK\n"

	printf "sysctl ... "
	if [ -r /etc/sysctl.conf ]; then
		echo "Setting sysctl variables:"
		sysctl -f /etc/sysctl.conf
	fi
	printf "OK\n"

	printf "mountall ... "
	mount -a
	printf "OK\n"

	printf "ldconfig ... "
	if [ -f ${ldconfig_command} ]; then
		echo "Creating a.out runtime link editor directory cache."
		${ldconfig_command} ${rc_flags}
	fi
	printf "OK\n"

	printf "ttys ... "
	ttyflags -a
	printf "OK\n"

	printf "setting securelevel ... "
	osecurelevel=$(sysctl -n kern.securelevel 2>&-)
	if [ $? != 0 ]; then
		echo "Can't set securelevel. (kern.securelevel sysctl not present.)"
		exit 1
	fi

	if [ -n "$securelevel" -a "$securelevel" != "$osecurelevel" ]; then
		if [ "$securelevel" -lt "$osecurelevel" ]; then
			echo "Can't lower securelevel."
			exit 1
		else
			echo -n "Setting securelevel: "
			sysctl -w kern.securelevel=$securelevel
		fi
	else
		if [ "$osecurelevel" = 0 ]; then
			echo -n "Setting securelevel: "
			sysctl -w kern.securelevel=1
		fi
 	fi
	printf "OK\n"

	printf "wrap030_start done.\n"
}

wrap030_stop()
{
	printf "unmounting all file systems ... "
	umount -a
	printf "OK\n"

	printf "wrap030_stop done.\n"
}

load_rc_config $name
run_rc_command "$1"