#	$NetBSD: Makefile.wrap030,v 1.95 2019/08/21 20:31:23 skrll Exp $

# Makefile for NetBSD
#
# This makefile is constructed from a machine description:
#	config machineid
# Most changes should be made in the machine description
#	/sys/arch/wrap030/conf/``machineid''
# after which you should do
#	config machineid
# Machine generic makefile changes should be made in
#	/sys/arch/wrap030/conf/Makefile.wrap030
# after which config should be rerun for all machines of that type.
#
# To specify debugging, add the config line: makeoptions DEBUG="-g"
# A better way is to specify -g only for a few files.
#
#	makeoptions DEBUGLIST="uvm* trap if_*"

MACHINE_ARCH=m68k
USETOOLS?=	no
NEED_OWN_INSTALL_TARGET?=no
.include <bsd.own.mk>

##
## (1) port identification
##
WRAP030=		$S/arch/wrap030
GENASSYM_CONF=	${WRAP030}/wrap030/genassym.cf

##
## (2) compile settings
##
CPPFLAGS+=	-Dwrap030
CFLAGS+=	-msoft-float
AFLAGS+=	-x assembler-with-cpp

##
## (3) libkern and compat
##
OPT_MODULAR=	%MODULAR%

##
## (4) local objects, compile rules, and dependencies
##
# for the Motorola 68040 Floating Point Software Product
.include "$S/arch/m68k/fpsp/Makefile.inc"

MD_OBJS=	locore.o
MD_LIBS=	${FPSP}
MD_CFILES=
MD_SFILES=	${WRAP030}/wrap030/locore.s

locore.o: ${WRAP030}/wrap030/locore.s assym.h
	${NORMAL_S}

.include "$S/arch/m68k/conf/Makefile.kern.m68k.inc"

##
## (5) link settings
##
LINKFORMAT=	-n
TEXTADDR?=	0

##
## (6) port specific target dependencies
##

# depend on CPU configuration
dma.o hpux_machdep.o locore.o machdep.o pmap.o pmap_bootstrap.o sys_machdep.o trap.o: Makefile

##
## (7) misc settings
##

##
## (8) config(8) generated machinery
##
%INCLUDES

%OBJS

%CFILES

%SFILES

%LOAD

%RULES

##
## (9) port independent kernel machinery
##
.include "$S/conf/Makefile.kern.inc"

##
## (10) Appending make options.
##
%MAKEOPTIONSAPPEND
